import os

# DB
DB_PATH = os.environ.get("PREMARKET_DB", "data/premarket.db")

# HTTP
HTTP_TIMEOUT = 30
HTTP_RETRIES = 3
HTTP_DELAY_MIN = 1.0
HTTP_DELAY_MAX = 3.0
USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"

# === FX Thresholds ===
FX_THRESHOLD_TWD = 0.1
FX_THRESHOLD_CNY = 0.005
FX_THRESHOLD_KRW = 5.0

# === Futures ===
FUTURES_VOLUME_LOOKBACK = 5

# === Chip ===
CHIP_MA_PERIOD = 20
CHIP_MA_MIN_DAYS = 5
PRICE_ZONE_LOW = -20
PRICE_ZONE_CONSOLIDATION = 5
PRICE_ZONE_HIGH = 20
